sudo: false

language: elixir

dist: trusty

matrix:
    include:
    - elixir: 1.8
      otp_release: 22.0
    - elixir: 1.9
      otp_release: 22.0
    - elixir: 1.10
      otp_release: 22.0

install: 
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get

script: mix test